name: Build, Test & Publish

on:
  push:
    branches: [ master ]

env:
  ASOFT_MAVEN_PGP_PRIVATE_KEY: ${{ secrets.ASOFT_MAVEN_PGP_PRIVATE_KEY }}
  ASOFT_MAVEN_PGP_PASSWORD: ${{ secrets.ASOFT_MAVEN_PGP_PASSWORD }}
  ASOFT_NEXUS_PASSWORD: ${{ secrets.ASOFT_NEXUS_PASSWORD }}
  ASOFT_NEXUS_USERNAME: ${{ secrets.ASOFT_NEXUS_USERNAME }}

jobs:
  deploy-project:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
          key: ${{ runner.os }}-konan-
          restore-keys: ${{ runner.os }}-konan-
      - name: Making gradlew executable
        run: chmod +x ./gradlew
        working-directory: .
      - name: publishing later-core
        run: ./gradlew :later-core:publish
        working-directory: .
      - name: publishing later-ktx
        run: ./gradlew :later-ktx:publish
        working-directory: .
      - name: publishing later-test-expect
        run: ./gradlew :later-test-expect:publish
        working-directory: .
      - name: Closing and Releasing Repositories
        run: ./gradlew :later-core:closeAndReleaseRepository
        working-directory: .
